bin/setup.py: StandardError -> Exception
When error happens:
  File "/buildarea/lyang1/wr9-project/wrlinux-x/bin/setup.py", line 975, in run_cmd
    raise StandardError(msg)
NameError: name 'StandardError' is not defined

Python 2 has an exception class called StandardError that has been
removed in Python 3. Use Exception instead.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>
Signed-off-by: Mark Hatle <mark.hatle@windriver.com>