local.conf.sample: Use d.getVar() for BB_NO_NETWORK
Issue: LIN1019-1420

The BB_NO_NETWORK maybe removed by sstate.bbclass:

localdata.delVar('BB_NO_NETWORK')

Then BB_FETCH_PREMIRRORONLY will '${BB_NO_NETWORK}' since it can't expand it,
then bb.utils.to_boolean('$BB_NO_NETWORK}') would raise an error:

Exception: ValueError: Invalid value for to_boolean: ${BB_NO_NETWORK}

Use "d.getVar() or 0" to fix the problem.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>